import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import AddTask from '../components/taskEntry/task_entry'
import Todo from '../components/Todo/todo'
import styles from '../styles/Home.module.css'



export default function Home() {
  const [todos, setTodos] = useState([
    {
      text: "",
      isDone: false
    }
  ]);
  console.log(todos)
  const addTodo = (text) => {
    const newTodo = [...todos, { text }];
    setTodos(newTodo);
  }
  const markTodoDone = (index) => {
    const newTodo = [...todos];
    newTodo[index].isDone = true;
    setTodos(newTodo);
  }
  const deleteTodo = (index) => {
    const newTodo = [...todos];
    newTodo.splice(index, 1);
    setTodos(newTodo);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AddTask addTodo={addTodo} />
        <div>
          {todos.map((todo, index) => (<Todo key={index} index={index} todo={todo} markTodo={markTodoDone} deleteTodo={deleteTodo} />))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/src/public/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
